### ISSUE TITLE
Improve Gitlab Webhook provisioning

### ISSUE THREAD

**Issue by benbz** [matrix-org/matrix-hookshot#256]
**Is your feature request related to a problem? Please describe.**

GitLab webhook provisioning is more involved than (e.g.) GitHub (!hookshot github repo <my repo name>). You need to:
* Find the webhook secret and instance name from your config
* Go to the GitLab UI and provision the webhook pointing at your Hookshot domain and using the secret above
* Create a state event in the appropriate room (which isn't obvious, e.g. #158)

**Describe the solution you'd like**

Given I can provide Hookshot with a GitLab PAT with API scope, Hookshot should be able to do lots of this for us:
* `!hookshot gitlab repo <gitlab instance> <repo>`
* It knows its own webhook secret and domain
* It calls appropriate APIs under https://docs.gitlab.com/ee/api/projects.html#hooks using the stored PAT to see whether the webhook exists and configure it appropriate
* It can create the state event in the current room like it does for GitHub
* Bonus points for `<repo>` accepting a GitLab group and (for GitLab premium) configuring a webhook against the group or (for non-premium GitLab) looping over the projects in that group (and any sub-groups) and configuring a webhook against each project

**Describe alternatives you've considered**
* Having a command to create/manage the state event would be helpful but I think we can go further
* Having the webhook be configured against the whole instance is probably possible but then would allow anyone with permissions to the Hookshot to create state events that would leak details of repositories in Gitlab that they don't necessarily have access to

**Additional context**
I've got a group with >20 repos in it. Most don't get touched often but would like Hookshot configure against them. Doing it all manually probably isn't super worthwhile

**Comment by Half-Shot** [comment]
This is definitively something we'd like to do, but due to some annoying config choices early on we have some problems: GitLab doesn't know it's own public domain, because each public domain is specified under the service config.

The API calls could be easily done however to create the hook, which is something we do for things like Figma.

The group idea is interesting, it would definitely be nice to have that though tracking where webhooks are configured is something I'd like to tackle carefully.

I'd hope for this to land release after next.
