### ISSUE TITLE
Hookshot requires GitLab maintainer access against a project to operate

### ISSUE THREAD

**Issue by averi** [matrix-org/matrix-hookshot#547]
The way hookshot works as follows:

1. Service Account created in GitLab
2. A token is generated out of the Service Account
3. The Service Account gets added to the relevant projects with maintainer access

This flow imposes a strong security risk as anyone with access to the credentials of the Service Account in Matrix can hijack the target GitLab project. Hookshot should allow users to set up a webhook manually (or via a different protected automation method) using a plain webhook URL and the provided token. The current workaround we're applying in GNOME is removing the SA user from the target GitLab project right after the webhook has been correctly generated.

**Comment by AndrewFerr** [comment]
As it turns out, the only reason why Hookshot needs Maintainer access on a project is so it can automatically add a webhook to it.  In the absence of this permission, an authorized user could simply manually add a webhook to the project, and Hookshot would bridge events as usual.

The only blocker is that Hookshot refuses to connect a GitLab project to a room if GitLab webhooks are enabled in Hookshot configuration & the requesting user (in Matrix) is not a Maintainer/Owner (in GitLab) of the project to be connected.  This will be addressed by #567.

**Comment by AndrewFerr** [comment]
Aha, correction: Generic Webhooks **do** support GitLab webhooks.  The fact that they put their secret in the URL doesn't prevent them from working with GitLab; all it means is that when entering the webhook's details in Settings > Webhooks on the GitLab page for a project, the "Secret token" has to be left empty, as the secret is part of the URL instead.

As long as the whole URL is kept secret, having the webhook secret as part of the URL shouldn't make it any less private.  Plus, Hookshot does its best to conceal these URLs: when adding one via the `!hookshot webhook <name>` bot command, it DMs you the URL instead of posting it in a group chat; and the configuration widget hides the URLs to anyone who doesn't have the authorization to edit them.

Closing this case, since it is indeed possible to set up a webhook manually as was requested.
