### ISSUE TITLE
Widget fetching but not posting entries

### ISSUE THREAD

**Issue by OddHouseGames** [matrix-org/matrix-hookshot#848]
I'm trying to use the Widget for RSS feeds in Element on the web and it is successfully fetching but not posting anything.

**Comment by Half-Shot** [comment]
Hey there :wave: . Can you give me the URL for your feed so I can investigate what's going on? If you rather it be confidential, you can DM me on Matrix via @Half-Shot:half-shot.uk.

**Comment by OddHouseGames** [comment]
Thanks, I'll send you a DM!

**Comment by Half-Shot** [comment]
So for this specific feed, I think the expectation is hookshot would post when there is an update to an entry rather than just new entries. We basically skip any `guid`s we've seen before in the RSS feed to avoid reposting, so the problem is likely there. I can't see any issues with new posts on our staging instance but I will check next time the feed updates.

It's probably a reasonable feature to allow reposting existing entries if the `pubDate` has changed although I don't think we want to do this as standard.
